### ISSUE TITLE
Number zero appears in HD section

### ISSUE THREAD

**Issue by hongquan** [helmuthdu/conky_colors#58]
In 1 of my ext4 filesystem, the bar, the free and used number don't show, but a number zero appear nearby:

![selection_010](https://cloud.githubusercontent.com/assets/314607/7331247/0a5f0034-eb3b-11e4-8a12-b2142950f789.png)

This is the output of _conkyHD1_

```
$ /usr/share/conkycolors/bin/conkyHD1                                                                                             
${voffset 4}
${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Root: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Home: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /home}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Documents: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Documents}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /home/quan/Documents}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Documents}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Documents}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Works: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Works}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /home/quan/Works}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Works}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Works}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Entertainment: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Entertainment}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /home/quan/Entertainment}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Entertainment}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Entertainment}${color}${font}

${voffset -10}
```

**Comment by hongquan** [comment]
When I remove _fs_bar_, it becomes like this:

![selection_012](https://cloud.githubusercontent.com/assets/314607/7331376/ffcc7a76-eb3e-11e4-8748-3406c8ff9ec9.png)

The script output now is:

```
$ /usr/share/conkycolors/bin/conkyHD1                                                                                             
${voffset 4}
${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Root: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /}%${color}${font}

${voffset -10}${offset 1}${color0}${color}${offset 24}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Home: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home}%${color}${font}

${voffset -10}${offset 1}${color0}${color}${offset 24}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Documents: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Documents}%${color}${font}

${voffset -10}${offset 1}${color0}${color}${offset 24}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Documents}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Documents}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Works: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Works}%${color}${font}

${voffset -10}${offset 1}${color0}${color}${offset 24}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Works}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Works}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Entertainment: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /home/quan/Entertainment}%${color}${font}

${voffset -10}${offset 1}${color0}${color}${offset 24}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /home/quan/Entertainment}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /home/quan/Entertainment}${color}${font}
```

**Comment by teeedubb** [comment]
Hi,

I think I am having the same issue:
![screenshot from 2015-09-06 22 50 51](https://cloud.githubusercontent.com/assets/3460068/9704434/d232e950-54e9-11e5-92ea-a73a2c35f4c2.png)

Output of /usr/share/conkycolors/bin/conkyHD1 (I cant see anything untoward)

${voffset 4}
${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Storage: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/storage}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/storage}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/storage}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/storage}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Osx: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/osx}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/osx}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/osx}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/osx}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Osx-recovery: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/osx-recovery}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/osx-recovery}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/osx-recovery}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/osx-recovery}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Kodibuntu: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/kodibuntu}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/kodibuntu}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/kodibuntu}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/kodibuntu}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Kubuntu: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/kubuntu}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/kubuntu}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/kubuntu}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/kubuntu}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Storage2: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/storage2}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/storage2}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/storage2}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/storage2}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Games-linux: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/games-linux}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/games-linux}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/games-linux}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/games-linux}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Win8-boot: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/win8-boot}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/win8-boot}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/win8-boot}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/win8-boot}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Win10-boot: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/win10-boot}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/win10-boot}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/win10-boot}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/win10-boot}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Win10: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/win10}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/win10}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/win10}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/win10}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Root: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Games-windows: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /mnt/games-windows}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /mnt/games-windows}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /mnt/games-windows}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /mnt/games-windows}${color}${font}

${voffset -10}${offset 0}${color0}${font ConkyColors:size=15}i${font}${color}${offset 6}${voffset -10}Sonata_volume: ${font Ubuntu:style=Bold:size=8}${color1}${fs_free_perc /media/tw/SONATA_VOLUME}%${color}${font}

${voffset -10}${offset 1}${color0}${fs_bar 4,17 /media/tw/SONATA_VOLUME}${color}${offset 10}${voffset -2}F: ${font Ubuntu:style=Bold:size=8}${color2}${fs_free /media/tw/SONATA_VOLUME}${color}${font} U: ${font Ubuntu:style=Bold:size=8}${color2}${fs_used /media/tw/SONATA_VOLUME}${color}${font}

${voffset -10}

**Comment by hongquan** [comment]
Was fixed.
